name: rf_loc_single_bs
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
  - nvidia
dependencies:
  - pip=23.3.1
  - python=3.11.8
  - conda-lock=1.4.0
  - hydra-core=1.3.2
  - pytorch-lightning=2.2.1
  - rich=13.3.5
  - scikit-image=0.22.0
  - scikit-learn=1.4.0
  - plotly=5.19.0
  - pytorch=2.2.1
  - pytorch-cuda=11.8
  - torchvision=0.17.1
  - seaborn=0.12.2
  - tqdm=4.65.0
  - python-dotenv=0.21.0
  - transformers=4.37.2
  - altair=5.0.1
  - tabulate=0.9.0
  - streamlit=1.32.0
  - scipy=1.11.4
  - numpy=1.26.4
  - pip:
      - aim==3.18.1
