_target_: src.algorithms.ERM

name: erm
allowable_errors: [ 1, 3, 5, 10, 30, 50, 100, 200 ]

groups_count: 2

compiled:
  _target_: src.utils.CompileParams
  fullgraph: False
  dynamic: null
  backend: inductor
  mode: null
  options: null
  disable: True