# @package _global_
name: validation_visualize
seed: 0
print_config: True
ignore_warnings: True

raw_data_path: ${oc.env:RAW_DATA_DIR}
predictions_path: ${oc.env:PREDICTIONS_PATH}/scenario2/2023-10-30_14-57-12
baseline_radius: 10

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True